name: Migrate Amplience Content Schemas and Content Type

on: 
  workflow_dispatch:
    inputs:
        environment:
            type: choice
            description: 'Deployment environment'
            options:
            - 'amplienceHub_qa_to_prod'
            - 'amplienceHub_dev_to_qa'
            required: true

jobs:
  build:
    runs-on: node:18.16.1
    environment: ${{ inputs.environment }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Export Amplience Content Schemas & Content Types from source, Update visualization URL, import to Destination
      uses: ./actions/headless-deploy-amplience